server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317 # default: 127.0.0.1:4317
ingester:
  trace_idle_period: 10s
  max_block_duration: 5m
compactor:
  compaction:
    block_retention: 1h
metrics_generator:
  storage:
    path: /var/tempo/metrics
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
